api_platform:
    title: Tienda online API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
            cors:
                allow_origin: ['http://tienda-online.local', 'http://localhost:3000']  # Añade localhost
                allow_headers: ['Content-Type', 'Authorization']
                allow_methods: ['GET', 'POST', 'OPTIONS']
    doctrine_mongodb_odm:
        enabled: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Document']
    enable_swagger_ui: true
    enable_docs: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
