doctrine_migrations:
    migrations_paths:
        'Migrations\Mysql': '%kernel.project_dir%/migrations/mysql'
        'Migrations\Postgres': '%kernel.project_dir%/migrations/postgres'
    enable_profiler: false
    storage:
        table_storage:
            table_name: doctrine_migration_versions
