doctrine:
    dbal:
        default_connection: mysql_connection
        connections:
            mysql_connection:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '8.0'
                driver: 'pdo_mysql'

            postgres_connection:
                url: '%env(resolve:DATABASE_URL_PGSQL)%'
                server_version: '16'
                logging: true
                driver: 'pdo_pgsql'
                charset: utf8

    orm:
        default_entity_manager: mysql_entity_manager
        entity_managers:
            mysql_entity_manager:
                connection: mysql_connection
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Mysql

            postgres_entity_manager:
                connection: postgres_connection
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Postgres

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
