# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null          # Symfony usa su gestor de sesión por defecto
        cookie_secure: auto       # Automáticamente asegura las cookies en HTTPS
        cookie_samesite: lax      # Mejora la compatibilidad de las cookies
        cookie_httponly: true     # Mejora la seguridad (solo accesible desde HTTP)
        gc_maxlifetime: 3600      # Tiempo de vida de la sesión en segundos


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
