framework:
    messenger:
        failure_transport: failed

        transports:
            # Configuración del transporte RabbitMQ
            async:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    exchange:
                        name: 'symfony'
                    queues:
                        email_queue: ~

            # Configuración del transporte de fallos para usar PostgreSQL en lugar de 'default'
            failed: 'doctrine://mysql_connection?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            'App\Message\*': async
            'App\Message\SendEmailMessage': async
