monolog:
    handlers:
        # Logs de INFO
        info:
            type: stream
            path: '%kernel.logs_dir%/info.log'
            level: info

        # Logs de DEBUG
        custom_debug:
            type: stream
            path: '%kernel.logs_dir%/debug.log'
            level: debug
            formatter: monolog.formatter.json  # Solo el nombre del formatter
            bubble: true

        # Logs de ERROR
        error:
            type: stream
            path: '%kernel.logs_dir%/error.log'
            level: error

        # Logs generales
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/main.log'
            level: notice
            max_files: 5

        # Logs críticos
        critical:
            type: fingers_crossed
            action_level: critical
            handler: critical_buffer
            excluded_http_codes: [404]

        critical_buffer:
            type: stream
            path: '%kernel.logs_dir%/critical.log'
