security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        register:
            pattern: ^/api/user/register
            stateless: true
            security: false

        login:
            pattern: ^/api/user/login
            stateless: true
            security: false

        test-email:
            pattern: ^/api/test-email
            stateless: true
            security: false

        index-data:
            pattern: ^/api/index-data
            stateless: true
            security: false

        search-data:
            pattern: ^/api/search-data
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: false
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
                default_target_path: /dashboard
            logout:
                path: logout
                target: /login
                invalidate_session: true  # Invalida la sesión del usuario

    access_control:
        - {path: ^/docs, roles: PUBLIC_ACCESS}
        - {path: ^/login$, roles: PUBLIC_ACCESS}
        - {path: ^/logout$, roles: IS_AUTHENTICATED_FULLY}
        - {path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY}
        - {path: ^/api/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/test-email, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/index-data, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api/search-data, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/api, roles: IS_AUTHENTICATED_FULLY}
        - {path: ^/admin, roles: ROLE_ADMIN}



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
